# Noah-Manuel Michael
# Created: 31.05.2023
# Last updated: 01.06.2023
# Get a more abstract version of the trees generated by the discodop-parser
# This script was pair-programmed with ChatGPT (v4)

import pandas as pd
import re
from nltk import Tree


def contains_verb(tree):
    """
    Recursive function to check if a tree or subtree contains a verb.
    :param tree: a tree parsed with nltk Tree
    :return: bool
    """
    if tree.label() == 'ww':
        return True
    else:
        return any(contains_verb(subtree) for subtree in tree if isinstance(subtree, Tree))


def summarize_tree(tree):
    """
    Recursive function to summarize a tree by replacing non-verb containing subtrees with their root node.
    :param tree: a tree parsed with nltk Tree
    :return: None
    """
    for i, subtree in enumerate(tree):
        if isinstance(subtree, Tree):
            if not contains_verb(subtree):
                tree[i] = Tree(subtree.label(), [])
            else:
                summarize_tree(subtree)


def remove_leaves(tree):
    """
    Recursive function to traverse the tree and remove leaf nodes, which in this case are position indicators.
    :param tree: a tree parsed with nltk Tree
    :return: None
    """
    for i, subtree in enumerate(tree):
        if isinstance(subtree, Tree):
            remove_leaves(subtree)
        elif isinstance(subtree, str):  # If leaf, remove it
            tree[i] = ""


def remove_let(tree):
    """
    Recursive function to traverse the tree and remove "let" labeled nodes (punctuation).
    :param tree: a tree parsed with nltk Tree
    :return: None
    """
    idx = 0
    while idx < len(tree):
        subtree = tree[idx]
        if isinstance(subtree, Tree):
            if subtree.label() == 'let':
                del tree[idx]
            else:
                remove_let(subtree)
                idx += 1
        else:
            idx += 1


def do_simplification(tree):
    """
    Execute the functions necessary to simplify the tree structures.
    :param tree: a tree parsed with nltk Tree
    :return: None
    """
    summarize_tree(tree)
    remove_leaves(tree)
    remove_let(tree)


def simplify_trees():
    """
    Run the script to simplify the stree structures obtained from the disco-dop parser.
    :return: None
    """
    for split in ['test', 'dev']:
        for correctness in ['correct', 'incorrect']:
            df = pd.read_csv(f'Data/{split}_{correctness}_parsed.tsv', encoding='utf-8', sep='\t', header=0)

            simplified_trees = []

            for tree_string in df['tree']:
                tree = Tree.fromstring(tree_string)
                do_simplification(tree)
                tree_str = re.sub(r'\s+', ' ', str(tree))
                tree_str = re.sub(r' \)', ')', tree_str)
                simplified_trees.append(tree_str)

            df['simple_tree'] = simplified_trees
            df.to_csv(f'Data/{split}_{correctness}_simplified.tsv', encoding='utf-8', sep='\t', index=False)

            print(f'{split.title()} data\'s {correctness} sentence trees simplified.')


if __name__ == '__main__':
    simplify_trees()
