# Noah-Manuel Michael
# Created: 31.05.2023
# Last updated: 31.05.2023
# Permute only verb positions in data for dataset creation
# Get a more abstract version of the trees generated by the discodop-parser

